name: Deploy
env:
  SOURCE_BRANCH: main
  PAGES_BRANCH: gh-pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: mkdocs build
      # Release the site to the gh-pages branch in a subdir "docs"
      # so that our site can be hosted at felis.alice-bob.com/docs
      - run: ghp-import site --force -p -x docs

      - name: Switch to $PAGES_BRANCH branch
        run: git checkout $PAGES_BRANCH

      - name: Copy CNAME & index.html from $SOURCE_BRANCH branch
        run: git checkout $SOURCE_BRANCH CNAME index.html

      - name: Add files to commit
        run: git add CNAME index.html

      - name: Commit CNAME & index.html
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m "Add CNAME & index.html"

      - name: Push changes
        run: git push origin $PAGES_BRANCH


